version: "3.8"
services:
  headnode:
    image: nsimakov/slurm_sim_head_node:4
    hostname: headnode
    shm_size: 64M
    command: ["sshd", "munged", "mysqld", "/opt/cluster/vctools/add_system_users.sh", "-loop"]
    # "/opt/cluster/vctools/start_head_node.sh" is intentionally removed here
    # run_vc.sh will start slurm services in right order and will track time
    networks:
      network1:
        ipv4_address: 172.32.0.11
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - '../micro3/job_traces:/opt/cluster/job_traces'
      - './log:/var/log/slurm'
      - './home:/home'
      - './../../slurm_sim_tools:/opt/cluster/slurm_sim_tools'
    cpuset: '0-3'
  n1:
    image: nsimakov/slurm_compute_node:3
    hostname: n1
    command: ["sshd", "munged", "/opt/cluster/vctools/start_compute_node.sh", "-loop"]
    networks:
      network1:
        ipv4_address: 172.32.1.101
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - '../micro3/job_traces:/opt/cluster/job_traces'
      - './compute_nodes_log/n1:/var/log/slurm'
      - './home:/home'
    cpuset: '4-7'
  n2:
    image: nsimakov/slurm_compute_node:3
    hostname: n2
    command: ["sshd", "munged", "/opt/cluster/vctools/start_compute_node.sh", "-loop"]
    networks:
      network1:
        ipv4_address: 172.32.1.102
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - '../micro3/job_traces:/opt/cluster/job_traces'
      - './compute_nodes_log/n2:/var/log/slurm'
      - './home:/home'
    cpuset: '4-7'
  n3:
    image: nsimakov/slurm_compute_node:3
    hostname: n3
    command: ["sshd", "munged", "/opt/cluster/vctools/start_compute_node.sh", "-loop"]
    networks:
      network1:
        ipv4_address: 172.32.1.103
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - '../micro3/job_traces:/opt/cluster/job_traces'
      - './compute_nodes_log/n3:/var/log/slurm'
      - './home:/home'
    cpuset: '4-7'
  n4:
    image: nsimakov/slurm_compute_node:3
    hostname: n4
    command: ["sshd", "munged", "/opt/cluster/vctools/start_compute_node.sh", "-loop"]
    networks:
      network1:
        ipv4_address: 172.32.1.104
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - '../micro3/job_traces:/opt/cluster/job_traces'
      - './compute_nodes_log/n4:/var/log/slurm'
      - './home:/home'
    cpuset: '4-7'
  m1:
    image: nsimakov/slurm_compute_node:3
    hostname:   m1
    command: ["sshd", "munged", "/opt/cluster/vctools/start_compute_node.sh", "-loop"]
    networks:
      network1:
        ipv4_address: 172.32.2.101
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - '../micro3/job_traces:/opt/cluster/job_traces'
      - './compute_nodes_log/  m1:/var/log/slurm'
      - './home:/home'
    cpuset: '4-7'
  m2:
    image: nsimakov/slurm_compute_node:3
    hostname:   m2
    command: ["sshd", "munged", "/opt/cluster/vctools/start_compute_node.sh", "-loop"]
    networks:
      network1:
        ipv4_address: 172.32.2.102
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - '../micro3/job_traces:/opt/cluster/job_traces'
      - './compute_nodes_log/  m2:/var/log/slurm'
      - './home:/home'
    cpuset: '4-7'
  m3:
    image: nsimakov/slurm_compute_node:3
    hostname:   m3
    command: ["sshd", "munged", "/opt/cluster/vctools/start_compute_node.sh", "-loop"]
    networks:
      network1:
        ipv4_address: 172.32.2.103
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - '../micro3/job_traces:/opt/cluster/job_traces'
      - './compute_nodes_log/  m3:/var/log/slurm'
      - './home:/home'
    cpuset: '4-7'
  m4:
    image: nsimakov/slurm_compute_node:3
    hostname:   m4
    command: ["sshd", "munged", "/opt/cluster/vctools/start_compute_node.sh", "-loop"]
    networks:
      network1:
        ipv4_address: 172.32.2.104
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - '../micro3/job_traces:/opt/cluster/job_traces'
      - './compute_nodes_log/  m4:/var/log/slurm'
      - './home:/home'
    cpuset: '4-7'
  b1:
    image: nsimakov/slurm_compute_node:3
    hostname:   b1
    command: ["sshd", "munged", "/opt/cluster/vctools/start_compute_node.sh", "-loop"]
    networks:
      network1:
        ipv4_address: 172.32.3.101
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - '../micro3/job_traces:/opt/cluster/job_traces'
      - './compute_nodes_log/  b1:/var/log/slurm'
      - './home:/home'
    cpuset: '4-7'
  g1:
    image: nsimakov/slurm_compute_node:3
    hostname:   g1
    command: ["sshd", "munged", "/opt/cluster/vctools/start_compute_node.sh", "-loop"]
    networks:
      network1:
        ipv4_address: 172.32.4.101
    volumes:
      - './results:/root/results'
      - './etc:/etc/slurm'
      - './vctools:/opt/cluster/vctools'
      - '../micro3/job_traces:/opt/cluster/job_traces'
      - './compute_nodes_log/  g1:/var/log/slurm'
      - './home:/home'
    cpuset: '4-7'
networks:
  network1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.32.0.0/21"
